---
# image:
#  file: .gitpod.Dockerfile

tasks:
  - name: Kali Hooks Playground
    init: |
      # bring in secret access tokens from gitpod user dashboard
      eval $(gp env -e)
      pnpm install
      [ ! -f .env.local ] && cp .env.example .env.local
      cd -
      # Install Foundry
      curl -L https://foundry.paradigm.xyz | bash
      source /home/gitpod/.bashrc
      foundryup
      gp sync-done build
    command: |
      pnpm playground
  - name: Shell
    init: gp sync-await build
    command: |
      bash
    openMode: split-right

vscode:
  extensions:
    - ms-vscode.vscode-typescript-tslint-plugin
    - bungcip.better-toml
    - esbenp.prettier-vscode
    - juanblanco.solidity

    - dbaeumer.vscode-eslint

ports:
  # allow front end to access backend api
  # https://www.gitpod.io/docs/config-ports#cors
  # frontend web app service : Node.js, React
  - port: 3000
    name: Kali Hooks
    onOpen: open-browser
    visibility: public

  - port: 3001-9999
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
